---
- name: configuring apache using child playbooks
  hosts: all
  tasks:
   - name: call multiple child playbooks
     include: "{{item}}"
     with_items:
      - install_apache.yml
      - edit_index.yml
      - service.yml
      - check_url_response.yml

...
