---
- name: create users and create files/dirs in user home dir
  hosts: all
  tasks:
   - name: create users
     user:
      name: "{{a}}"
      password: "{{b}}"
      uid: "{{c}}"
      home: "{{d}}"
   - name: create files/dirs in users home dir
     file:
      name: "{{e}}"
      state: "{{f}}"






...
