---
- name: install required s/w's for ci-cd
  hosts: all
  tasks:
   - name: install s/w's
     apt:
      name: "{{item.a}}"
      state: present 
      update_cache: "{{item.b}}"
     with_items:
      - {a: git,b: yes}
      - {a: openjdk-8-jdk,b: no}
      - {a: maven,b: no}
      - {a: tomcat9,b: no}
- name: continuous download and build
  hosts: devserver
  tasks:
   - name: download the code created by developers
     git:
      repo: https://github.com/intelliqittrainings/maven.git
      dest: /tmp/mygit
   - name: create an artifact from the above code
     shell: cd /tmp/mygit;mvn package
   - name: fetch the artifact from devserver to controller
     fetch:
      src: /tmp/mygit/webapp/target/webapp.war
      dest: /tmp
- name: continuous deployment and testing
  hosts: qaserver
  tasks:
   - name: deploy artifact into tomcat on qaserver
     copy:
      src: /tmp/172.31.50.7/tmp/mygit/webapp/target/webapp.war
      dest: /var/lib/tomcat9/webapps/testapp.war
   - name: restart tomcat
     service:
      name: tomcat9
      state: restarted
   - name: download the selenium test scripts
     git:
      repo: https://github.com/intelliqittrainings/FunctionalTesting.git
      dest: /tmp/test-git
   - name: execute the selenium test scripts
     shell: java -jar /tmp/test-git/testing.jar
- name: continuous delivery
  hosts: prodserver
  tasks:
   - name: deploy the artifact into prodserver tomcat
     copy:
      src: /tmp/172.31.50.7/tmp/mygit/webapp/target/webapp.war
      dest: /var/lib/tomcat9/webapps/prodapp.war
...  


