---
- name: install jenkins and required s/w's
  hosts: jenkinsserver
  tasks:
   - name: install required s/w's
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: openjdk-8-jdk,b: yes}
      - {a: git,b: no}
      - {a: maven,b: no}
   - name: download jenkins.war
     get_url:
      url: https://get.jenkins.io/war-stable/2.277.1/jenkins.war
      dest: /home/ubuntu
- name: install tomcat9 and required s/w's
  hosts: appserver
  tasks:
   - name: install tomcat9 and tomcat9-admin
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: tomcat9,b: yes}
      - {a: tomcat9-admin,b: yes}
   - name: copy tomcat-users.xml file
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat9
   - name: restart tomcat
     service:
      name: tomcat9
      state: restarted

...
